load("//bazel:console_cc.bzl", "console_cc_binary")

console_cc_binary(
    name = "styled_text",
    srcs = ["styled_text.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "animation",
    srcs = ["animation.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "custom_animation",
    srcs = ["custom_animation.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "simple_flag",
    srcs = ["simple_flag.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "vector_flag",
    srcs = ["vector_flag.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "custom_flag",
    srcs = ["custom_flag.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "custom_flag2",
    srcs = ["custom_flag2.cc"],
    deps = ["//:console"],
)

console_cc_binary(
    name = "sub_parser",
    srcs = ["sub_parser.cc"],
    deps = ["//:console"],
)
